name: Build Offline APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip openjdk-17-jdk
          npm install -g cordova

      - name: Unzip source code
        run: unzip new-myapp.zip -d www

      - name: Create Cordova project
        run: |
          cordova create myapp com.example.myapp "Child Learning"
          cd myapp
          cordova platform add android
          rm -rf www
          mv ../www www

      - name: Build APK
        run: |
          cd myapp
          cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: myapp/platforms/android/app/build/outputs/apk/release/app-release.apk
